ability to requeue jobs upto max_restarts for non-zero exit codes, mask bad exit codes due to termination
Signed-off-by: Sanyam Kapoor <www@sanyamkapoor.com>

diff --git a/pkgs/core/src/slurm_compose/api/templates/slurm.sh.j2 b/pkgs/core/src/slurm_compose/api/templates/slurm.sh.j2
--- a/pkgs/core/src/slurm_compose/api/templates/slurm.sh.j2
+++ b/pkgs/core/src/slurm_compose/api/templates/slurm.sh.j2
@@ -8,6 +8,27 @@
 #SBATCH {{ arg }}
 {% endfor %}
 
+function maybe_sbatch_requeue {
+    max_restarts={{ max_restarts }}
+    if [[ (-n "${SLURM_JOB_ID}") && ($max_restarts -gt 0) ]]; then
+        restarts=${SLURM_RESTART_COUNT:-0}
+
+        if (( restarts < max_restarts )); then
+            requeue_job_id="${SLURM_JOB_ID}"
+            if [[ (-n "${SLURM_ARRAY_JOB_ID:-}") && (-n "${SLURM_ARRAY_TASK_ID:-}") ]]; then
+                requeue_job_id="${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"
+            fi
+
+            echo "[INFO] Requeueing sbatch job ${requeue_job_id} (attempt $(( restarts + 1 ))/${max_restarts})"
+            if ! scontrol requeue "${requeue_job_id}"; then
+                echo "[ERROR] Failed to requeue sbatch job ${requeue_job_id}."
+            fi
+        else
+            echo "[ERROR] Max restarts (${max_restarts}) reached."
+        fi
+    fi
+}
+
 {% for k, v in env.items() %}
 export {{ k }}="{{ v }}"
 {% endfor %}
@@ -31,18 +52,23 @@ export {{ k }}="{{ v }}"
 
 {{ step.args | trim }}
 } & step_pids+=($!)
-# unset {{ step.env.keys() | join(" ") }}
 
 {% if not loop.last and step_delay is defined %}
 sleep {{ step_delay }}
 {% endif %}
 {% endfor %}
 
-## Waits for any step to finish, and then terminates all returning the exit code.
-wait -n "${step_pids[@]}"
-exit_code=$?
+## Wait for any step to finish, and terminate pids.
+exit_code=0
+wait -n "${step_pids[@]}" || exit_code=$?
 for pid in "${step_pids[@]}"; do
-    kill -TERM "$pid" 2>/dev/null
+    kill -TERM "$pid" 2>/dev/null || true
 done
-wait "${step_pids[@]}" 2>/dev/null
+wait "${step_pids[@]}" 2>/dev/null || true
+
+## Attempt requeue for non-zero exit codes.
+if [[ $exit_code -ne 0 ]]; then
+    maybe_sbatch_requeue
+fi
+
 exit $exit_code
